#!/usr/bin/env bash

# Custom Alias of @arv-anshul
alias act="source .venv/bin/activate"
alias brs="brew services"
alias cls="clear"
alias dev="cd ~/Developer"
alias dk="docker"
alias dkc="docker-compose"
alias flushdns="sudo killall -HUP mDNSResponder; dscacheutil -flushcache;"
alias lsa="ls -lahFG"
alias py="python"
alias zshs="source ~/.zshrc"
alias zx="exit"

# Alias for GIT
alias g="git"
alias ga="git add"
alias gac="git add -A && git commit -am"
alias gb="git branch"
alias gch="git checkout"
alias gcm="git checkout main"
alias gd="git diff"
alias gf="git fetch origin"
alias gfa="git fetch --all"
alias glog="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --branches"
alias gpull="git pull"
alias gpush="git push"
alias gra="git remote add"
alias grf="git reflog"
alias grv="git remote -v"
alias gs="git status"
alias gss="git status -s"
alias gc="git commit"
alias gsw="git switch"

# utilities
function loadenv() {
    local filePath="${1:-.env}"
    [ -f "$filePath" ] && export $(grep -v '^#' "$filePath" | xargs)
}

function pycls() {
    find . -maxdepth 5 -type f -name ".DS_Store" -delete
    find . -maxdepth 5 -type d -name ".venv" -prune -o -type d -name "__pycache__" -exec rm -rfv {} \; 2>/dev/null
    find . -maxdepth 5 -type d -name ".ipynb_checkpoints" -exec rm -rfv {} \; 2>/dev/null
    find . -maxdepth 5 -type d -name ".ruff_cache" -exec rm -rfv {} \; 2>/dev/null
    find . -maxdepth 5 -type d -name ".venv" -prune -o -type f -name "*.pyc" -exec rm -fv {} \; 2>/dev/null
}

function colormap() {
    range_start=${1:-1}
    range_end=${2:-255}

    for i in $(seq $range_start $range_end); do
        echo -en "\e[48;5;${i}m  ${(l:3::0:)i}  \e[0m "
        [[ $((i % 10)) -eq 0 ]] && echo
    done
    return 0
}
