#!/usr/bin/env bash

# Custom Alias of @arv-anshul
alias act="source .venv/bin/activate"
alias brs="brew services"
alias cls="clear"
alias dev="cd ~/Developer"
alias flushdns="sudo killall -HUP mDNSResponder; dscacheutil -flushcache;"
alias jg="just -g"
alias lsa="ls -lahFG"
alias py="python"
alias zshs="source ~/.zshrc"
alias zx="exit"

# Alias for GIT
alias g="git"
alias ga="git add"
alias gac="git commit -am"
alias gb="git branch"
alias gch="git checkout"
alias gcm="git checkout main"
alias gd="git diff"
alias glog="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --branches"
alias gra="git remote add"
alias grf="git reflog"
alias grv="git remote -v"
alias gs="git status"
alias gss="git status -s"
alias gc="git commit"
alias gsw="git switch"

# utilities
function colormap() {
    range_start=${1:-1}
    range_end=${2:-255}

    for i in $(seq $range_start $range_end); do
        echo -en "\e[48;5;${i}m  ${(l:3::0:)i}  \e[0m "
        [[ $((i % 10)) -eq 0 ]] && echo
    done
    return 0
}
