"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """
$status\
$directory\
$git_branch\
$git_status\
$character\
"""

right_format = """
$python\
$nodejs\
$rust\
$docker_context\
$cmd_duration
"""

palette = "hex"

[palettes.hex]
black = "#000000"
blue = "#2472C8"
cyan = "#11A8CD"
green = "#0DBC79"
magenta = "#BC3FBC"
red = "#CD3131"
white = "#E5E5E5"
yellow = "#E5E510"

[character]
format = "$symbol "
success_symbol = ""
error_symbol = "[✖](bold italic red)"

[status]
disabled = false
style = "black"
format = "[](fg:$style)[$status](bold fg:red bg:$style)[](fg:$style)"

[cmd_duration]
style = "black"
format = "[](fg:$style)[󰥔 $duration](bg:$style)[](fg:$style)"
min_time = 1000

[directory]
style = "red"
format = "[](fg:$style)[$path](bg:$style)[](fg:$style)"

[git_branch]
style = "blue"
format = "[](fg:$style)[$symbol$branch](bg:$style)"
symbol = ""

[git_status]
style = "blue"
format = "[( $all_status$ahead_behind)](bold italic bg:$style)[](fg:$style)"

[python]
symbol = "󰌠"
style = "green"
format = "[](fg:$style)[$symbol( $version)[( \\($virtualenv\\))](bold bg:$style)](bg:$style)[](fg:$style)"

[rust]
symbol = "󱘗"
style = "red"
format = "[](fg:$style)[$symbol( $version)](bg:$style)[](fg:$style)"

[docker_context]
symbol = "󰡨"
style = "cyan"
format = "[](fg:$style)[$symbol ($context)](bg:$style)[](fg:$style)"

[nodejs]
symbol = ""
style = "green"
format = "[](fg:$style)[$symbol( $version)](bg:$style)[](fg:$style)"
