#!/usr/bin/env bash

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

# Homebrew
export PATH=/opt/homebrew/bin:$PATH
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

# Basic aliases
source $HOME/.config/.aliases

# ZSH: Basic Plugins
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/opt/zsh-fast-syntax-highlighting/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

## zsh-completions
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
    FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
    autoload -Uz compinit
    compinit
fi

# Starship: Shell Prompt
if type starship &>/dev/null; then
    eval "$(starship init zsh)"
fi

# sync rust and cargo bins
export PATH="/opt/homebrew/opt/rustup/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

# uv: python package manager
export PATH="$HOME/.local/bin:$PATH"

if [ -e "$HOME/.local/bin/uv" ]; then
    eval "$(uv generate-shell-completion zsh)"
fi

# ruff: formating and linting tool for python
export RUFF_NO_CACHE="true"
