#!/usr/bin/env bash

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

# Homebrew
export PATH=/opt/homebrew/bin:$PATH
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

# Basic aliases
source $HOME/.config/.aliases

# ZSH: Basic Plugins
source "$(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh"
source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$(brew --prefix)/opt/zsh-fast-syntax-highlighting/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"

## zsh-completions
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
    FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
    autoload -Uz compinit
    compinit
fi

# Starship: Shell Prompt
if type starship &>/dev/null; then
    eval "$(starship init zsh)"
fi

# Third party commands must be written in "$HOME/.zshrc.local"
ZSHRC_LOCAL="$HOME/.zshrc.local"

if [ -e "$ZSHRC_LOCAL" ]; then
    source "$ZSHRC_LOCAL"
else
    echo "Missing $ZSHRC_LOCAL"
fi
