# Global Taskfile of arv-anshul at "~/Developer/dotfiles"
# Know more about Taskfile: https://taskfile.dev

version: 3

env:
  MD_BADGES_PY: https://gist.githubusercontent.com/arv-anshul/f4ccfd9258f24ffa9769dfca9b9e091b/raw/12100d8528480c8a9c76e9f319bd39169de08aae/md_badges.py
  PYTHON: python3

vars:
  IDE:
    sh: \[ -n "$ZED_TERM" ] && echo 'zed' || echo 'code'
  GLOBAL_PYPROJECT: ~/Developer/pyproject.toml
  GLOBAL_TASKFILE: ~/Developer/Taskfile.yaml
  PRE_COMMIT_YAML: .pre-commit-config.yaml

tasks:
  default:
    desc: Print intro of arv-anshul
    cmds:
      - echo "Hello, I am Anshul and I'm a Data Scientist."
      - echo "GitHub   - https://github.com/arv-anshul"
      - echo "LinkedIn - https://linkedin.com/in/arv-anshul"
    silent: true
  open:
    desc: Open global Taskfile in IDE
    cmd: "{{.IDE}} {{.GLOBAL_TASKFILE}}"
  install-hooks:
    desc: Install pre-commit hooks
    cmd: pre-commit install --install-hooks -c $PRE_COMMIT_YAML
  pc:
    desc: Run pre-commit on staged files
    cmd: pre-commit run -c $PRE_COMMIT_YAML
  pc-all:
    desc: Run pre-commit on all files
    cmd: pre-commit run --all-files -c $PRE_COMMIT_YAML
  pyproject:
    aliases: [pyp, ppy]
    desc: Open global pyproject.toml in IDE
    cmd: "{{.IDE}} {{.GLOBAL_PYPROJECT}}"
  badge:
    # task badges -- python,pandas,polars,fastapi
    aliases: [badges]
    desc: CLI tool for simpleicons mardown badges
    cmd: curl -sSL $MD_BADGES_PY | $PYTHON - {{.CLI_ARGS}}
    silent: true
  week:
    desc: Print current week number of the year
    cmd: echo "Current week number is $(date +%V)."
    silent: true
