# Global Taskfile of arv-anshul at "~/Developer/dotfiles"
# Know more about Taskfile: https://taskfile.dev

version: 3

env:
  MD_BADGES_PY: https://gist.githubusercontent.com/arv-anshul/f4ccfd9258f24ffa9769dfca9b9e091b/raw/12100d8528480c8a9c76e9f319bd39169de08aae/md_badges.py
  PYTHON: python3

vars:
  IDE:
    sh: \[ -n "$ZED_TERM" ] && echo 'zed' || echo 'code'
  GLOBAL_PYPROJECT: ~/Developer/pyproject.toml
  GLOBAL_TASKFILE: ~/Developer/Taskfile.yaml

tasks:
  default:
    desc: Print intro of arv-anshul
    cmds:
      - echo "Hello, I am Anshul and I'm a Data Scientist."
      - echo "GitHub   - https://github.com/arv-anshul"
      - echo "LinkedIn - https://linkedin.com/in/arv-anshul"
      - echo
      - task -a
    silent: true

  open:
    desc: Open global Taskfile in IDE
    cmd: "{{.IDE}} {{.GLOBAL_TASKFILE}}"

  install-hooks:
    desc: Install pre-commit hooks
    dir: "{{.USER_WORKING_DIR}}"
    cmd: pre-commit install --install-hooks

  pc:
    desc: Run pre-commit on staged files
    dir: "{{.USER_WORKING_DIR}}"
    cmd: pre-commit run

  pc-all:
    desc: Run pre-commit on all files
    dir: "{{.USER_WORKING_DIR}}"
    cmd: pre-commit run --all-files

  pyproject:
    aliases: [pyp, ppy]
    desc: Open global pyproject.toml in IDE
    cmd: "{{.IDE}} {{.GLOBAL_PYPROJECT}}"

  badge:
    # task badges -- python,pandas,polars,fastapi
    aliases: [badges]
    desc: CLI tool for simpleicons mardown badges
    cmd: curl -sSL $MD_BADGES_PY | $PYTHON - {{.CLI_ARGS}}
    silent: true

  week:
    desc: Print current week number of the year
    cmd: echo "Current week number is $(date +%V)."
    silent: true

  brew:
    desc: Run brew update, cleanup and doctor
    cmds:
      - brew update
      - brew cleanup --prune=all
      - brew upgrade -n
      - brew doctor

  setup-project:rye:
    desc: Setup python any project using uv
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - rye init -r requirements.txt {{.CLI_ARGS}}
      - rye sync
      - rye fmt
      - rye lint

  setup-project:uv:
    desc: Setup python any project using uv
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - uv venv
      - uv pip install -r requirements.txt
      # TODO: add ruff format & check here
