"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$character\
"""

right_format = """
$python\
$rust\
$docker_context\
(
[](fg:arv_custom)
${custom.github}\
${custom.mkdocs}\
${custom.vscode}\
${custom.pre-commit}\
[](fg:arv_custom)
)
"""

palette = "arv-anshul-color"

[palettes.arv-anshul-ansi]
arv_dir = "203"
arv_docker = "026"
arv_git = "063"
arv_python = "028"
arv_rust = "131"
arv_custom = "236"

[palettes.arv-anshul-color]
arv_dir = "bright-red"
arv_docker = "bright-blue"
arv_git = "blue"
arv_python = "green"
arv_rust = "red"
arv_custom = "black"

[character]
format = "$symbol "
success_symbol = ""
error_symbol = "[✖](bold italic red)"

[directory]
style = "arv_dir"
format = "[](fg:$style)[$path](bold bg:$style)[](fg:$style)"

[git_branch]
style = "arv_git"
format = "[](fg:$style)[$symbol$branch](bg:$style)"
symbol = ""

[git_status]
style = "arv_git"
format = "[( $all_status$ahead_behind)](bold italic bg:$style)[](fg:$style)"
ahead = "󰑣"
behind = ""
modified = ""

[python]
symbol = ""
style = "arv_python"
format = "[](fg:$style)[$symbol( $version)[( \\($virtualenv\\))](bold bg:$style)](bg:$style)[](fg:$style)"

[rust]
symbol = "󱘗"
style = "arv_rust"
format = "[](fg:$style)[$symbol( $version)](bg:$style)[](fg:$style)"

[docker_context]
symbol = ""
style = "arv_docker"
format = "[](fg:$style)[$symbol ($context)](bg:$style)[](fg:$style)"

[custom.github]
detect_folders = [".github"]
format = "[$symbol]($style)"
style = "bg:arv_custom"
symbol = " "

[custom.mkdocs]
detect_files = ["mkdocs.yaml", "mkdocs.yml"]
detect_folders = ["docs"]
format = "[$symbol]($style)"
style = "bg:arv_custom"
symbol = "󱔗 "

[custom.pre-commit]
detect_files = [".pre-commit-config.yaml", ".pre-commit-config.yml"]
format = "[$symbol]($style)"
style = "bg:arv_custom"
symbol = "󰛢"

[custom.vscode]
detect_folders = [".vscode"]
format = "[$symbol]($style)"
style = "bg:arv_custom"
symbol = "󰨞 "
