"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """
[](arv_dark)\
$directory\
[](fg:arv_dark bg:arv_green)\
$git_branch\
$git_status\
[](fg:arv_green) 
"""

right_format = """
[](arv_dark)\
$python\
$docker_context\
$time\
[](arv_dark)\
"""

palette = "arv-anshul"

[palettes.arv-anshul]
arv_blue = "30"
arv_brown = "3"
arv_dark = "238"
arv_green = "64"
arv_vanilla = "230"

[directory]
style = "bg:arv_dark fg:arv_vanilla"
format = "[$path ]($style)"

[git_branch]
style = "bg:arv_green"
format = "[[ $symbol$branch ](fg:arv_vanilla bg:arv_green)]($style)"
symbol = " "

[git_status]
style = "bg:arv_green"
format = "[[($all_status$ahead_behind )](bold italic fg:arv_vanilla bg:arv_green)]($style)"
# Use Nerd Fonts
# ahead = "󱓞"
# behind = ""
# modified = ""

[python]
symbol = ""
style = "bg:arv_blue"
format = "[[ $symbol( $version)[( \\($virtualenv\\))](bold $style) ](fg:arv_vanilla bg:arv_blue)]($style)"

[docker_context]
symbol = ""
style = "bg:arv_brown"
format = "[[ $symbol( $context) ](fg:arv_vanilla bg:arv_brown)]($style)"
