"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """
$character\
$directory\
$git_branch\
$git_status\
"""

right_format = """
$python\
$docker_context\
"""

palette = "arv-anshul"

[palettes.arv-anshul]
arv_blue = "30"
arv_red = "203"
arv_brown = "3"
arv_dark = "238"
arv_green = "64"
arv_vanilla = "230"
arv_purple = "056"

[character]
format = "$symbol "
success_symbol = ""
error_symbol = "[✖](bold italic red)"

[directory]
style = "bg:arv_dark fg:arv_vanilla"
format = "[](fg:arv_dark)[$path]($style)[](fg:arv_dark)"

[git_branch]
style = "fg:arv_vanilla bg:arv_green"
format = "[](fg:arv_green)[$symbol $branch ]($style)"
symbol = ""

[git_status]
style = "fg:arv_vanilla bg:arv_green"
format = "[($all_status$ahead_behind)](bold italic $style)[](fg:arv_green) "
# Use Nerd Fonts
# ahead = "󱓞"
# behind = ""
# modified = ""

[python]
symbol = ""
style = "fg:arv_vanilla bg:arv_blue"
format = "[](fg:arv_blue)[$symbol ($version)[( \\($virtualenv\\))](bold $style)]($style)[](fg:arv_blue)"

[docker_context]
symbol = ""
style = "fg:arv_vanilla bg:arv_red"
format = "[](fg:arv_red)[$symbol ($context)]($style)[](fg:arv_red)"
